channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.6
  - python-dotenv=0.21
  - numpy=1.23
  - python=3.11
  - openpyxl=3.0
  - python-kaleido=0.2
  - ipykernel=6.17
  - pandas=1.5
  - scipy=1.9
  - notebook=6.5
  - plotly=5.11
  - seaborn=0.12
  - make=4.3
  - pip=22.3
platforms:
  - win-64
